FizzBuzz - Python code four
Ganeshbabu18/SDET_PYTHON pull request #13
Opened 2023-05-16 05:01 UTC by Ganeshbabu18

2023-05-16 07:13 UTC, amitsahu8 approved these changes

2023-05-16 07:14 UTC, amitsahu8 requested changes

2023-05-16 07:14 UTC, amitsahu8 commented on FizzBuzz.py
> +for i in range(1, number+1):
resolve the conflicts and this is not medium complexity problem

2023-05-18 06:31 UTC, Ganeshbabu18 commented on FizzBuzz.py
> +for i in range(1, number+1):
@amitsahu8  Noted

2023-05-18 06:36 UTC, Ganeshbabu18 commented on FizzBuzz.py
> +for i in range(1, number+1):
@amitsahu8  Branch conflicts resolved

2023-05-18 08:26 UTC, merged