Verify password - Ninth Code
Ganeshbabu18/SDET_PYTHON pull request #18
Opened 2023-06-02 08:57 UTC by Ganeshbabu18

2023-06-06 13:42 UTC, amitsahu8 approved these changes

2023-06-06 13:43 UTC, amitsahu8 requested changes

2023-06-06 13:43 UTC, amitsahu8 commented on Verify_Password.py
> +    length_criteria = len(password) >= 8
resolve conflicts

2023-06-07 07:05 UTC, Ganeshbabu18 commented on Verify_Password.py
> +    length_criteria = len(password) >= 8
Conflicts resolved. kindly verify

2023-06-07 07:15 UTC, amitsahu8 approved these changes

2023-06-07 07:16 UTC, merged